### ISSUE TITLE
회원가입 페이지

### ISSUE THREAD

**Issue by rayodesol** [Drew-Choi/FOVE-Frontend#14]
**Description**
- 회원가입 페이지 제작

**Todo**
- [x] 리듀서 만들기 & 리듀서 하나로 합치기(현재는 하나뿐)
- [x] src > index.js 에 Provider 추가
- [x] 프론트 회원가입 구현 (필수 값, 비밀번호 확인, 아이디 중복 검사)
- [x] axios 에러 처리
- [x] 아이디 중복 검사 버튼 만들기
- [x] 일단 자동 로그인 가능

**ETC**
- 백과 연결 병행 중
- 5개 파일 작성/수정
