### ISSUE TITLE
상품 이미지 (SAMPLE) 수집 

### ISSUE THREAD

**Issue by shinsangah** [Drew-Choi/FOVE-Frontend#52]
**Description**
- 

**Todo**
- [ ] BEANIE 아이템 별 컬러 2~3개짜리 30 종류 수집 
- [ ] HAT 아이템 별 컬러 2~3개짜리 30 종류 수집
- [ ] MUFFLER 아이템 별 컬러 2~3개짜리 30 종류 수집
- [ ] 'Public' 폴더에 이미지 넣어놓기

**ETC**
-

**Comment by shinsangah** [comment]
HAT, MUFFLER 빼는 것인지 확인 필요..
STORE 카테고리 언젠가 바껴있음!
