### ISSUE TITLE
상품페이지 → SIZE&FIT → Product Mesurements (상세사이즈 모달창)

### ISSUE THREAD

**Issue by shinsangah** [Drew-Choi/FOVE-Frontend#96]
**Description**
- 상품 상세페이지 → SIZE&FIT → Product Mesurements (상세사이즈 모달창)

**Todo**
- [ ] SIZE&FIT 클릭 → 상세사이즈 모달창 제작하기
- [ ] 'BEANIE' SIZE&FIT 
- [ ] 'HAT' SIZE&FIT
- [ ] 'MUFFLER' SIZE&FIT 

**ETC**
-
